name: "Push docker image to GCR"

on:
  release:
    types: [published]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  push-docker-image:
    if: ${{ github.event.pull_request.merged || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            GITHUB_PERSONAL_TOKEN=${{ secrets.TK_REPO_ACCESS }}
          platforms: linux/amd64
          push: true
          tags: |
            gcr.io/evmchain/taiko-client:latest
