name: "CI"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      TK_REPO_ACCESS: ${{ secrets.TK_REPO_ACCESS }}
      CLIENT_DIR: taiko-client
      TAIKO_MONO_DIR: taiko-mono

    steps:
      - uses: actions/checkout@v3
        with:
          repository: taikochain/taiko-client
          path: ${{ env.CLIENT_DIR }}

      - uses: actions/checkout@v3
        with:
          repository: taikochain/taiko-mono
          token: ${{ secrets.TK_REPO_ACCESS }}
          path: ${{ env.TAIKO_MONO_DIR }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15

      - name: Install protocol dependences
        working-directory: ${{ env.TAIKO_MONO_DIR }}
        run: cd ./packages/protocol && yarn

      - name: Build
        working-directory: ${{ env.CLIENT_DIR }}
        run: make build

      - name: Lint
        working-directory: ${{ env.CLIENT_DIR }}
        run: make lint

      - name: Test
        working-directory: ${{ env.CLIENT_DIR }}
        run: |
          TAIKO_MONO_DIR=${GITHUB_WORKSPACE}/${TAIKO_MONO_DIR} COMPILE_PROTOCOL=true make test
